config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#get 'welcome/alphahome' , to: 'welcome#home'
get 'alphahome' , to: 'pages#home'
#root 'alphahome' , to: 'welcome#home'
#get 'welcome/alphaabout' , to: 'welcome#about'
get 'alphaabout' , to: 'pages#about'
get 'alphafirst' , to: 'pages#first'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def alphahome

	end

	def alphaabout

	end
	def alphafirst

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is the alphaabout page </h1>

<!--%= link_to 'Home', welcome_alphahome_path %-->
<%= link_to 'Home', alphahome_path %>

app/views/pages/first.html.erb
<%= link_to 'Home', alphahome_path %>
<br>
<br>
<br>
<br>

<h><center>
		<b>
			<u>
				<font size="12">
					Page Title
				</font>
			</u>
		</b>
	</center> 
</h>
<br>
<br>
<br>
<br>

<ul> </ul>
<center>

<!--b>
	<font size="4">
	Contact
	</font>
</b>
<tab>
	<tab>
		<b>
			<font size="4">
				Contact
			</font>
		</b>
	</tab>
</tab>

<tab>
	<tab>
		<b>
			<font size="4">
				Search
			</font>
		</b>
	</tab>
</tab>
	
<br-->

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
<body {font-family: "Lato", sans-serif;}
 /*background-color: #111*/
.tablink {
    background-color: #555;
    color: white;
    float: left;
    border: none;
    outline: none;
    cursor: pointer;
    padding: 14px 16px;
    font-size: 17px;
    width: 25%;
}

.tablink:hover {
    background-color: #777;
}

/* Style the tab content */
/*.tabcontent {
    color: white;
    display: none;
    padding: 0.1px;
    text-align: center;
}*/

#Home {background-color:red;}
#About {background-color:green;}
#Contact {background-color:blue;}
#Search {background-color:orange;}
</style>
</head>
<body>

<p>Click on the buttons inside the tabbed menu:</p>

<div id="Home" class="tabcontent">
  <h1>Home</h1>
  <p>This is Home Page.</p>
</div>

<div id="About" class="tabcontent">
  <h1>About</h1>
  <p>This is About Page.</p> 
</div>

<div id="Contact" class="tabcontent">
  <h1>Contact</h1>
  <p>This is Contact Page.</p>
</div>

<div id="Search" class="tabcontent">
  <h1>Search</h1>
  <p>This is Search Page.</p>
</div>

<button class="tablink" onclick="openCity('Home', this, 'red')" id="defaultOpen">Home</button>
<button class="tablink" onclick="openCity('About', this, 'green')">About</button>
<button class="tablink" onclick="openCity('Contact', this, 'blue')">Contact</button>
<button class="tablink" onclick="openCity('Search', this, 'orange')">Search</button>

<script>
function openCity(cityName,elmnt,color) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablink");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].style.backgroundColor = "";
    }
    document.getElementById(cityName).style.display = "block";
    elmnt.style.backgroundColor = color;

}
// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>
     
</body>
_________________________________________________________________________
<br>
<br>
<br>
<br>

</center>

<style>
table,th,td {
	border: 1px solid black;
}
</style>

<center>
	<table>
		<tr>
			<th> User Name : 
				<textarea autocomplete="arun"> </textarea> </th>
		</tr>

		<tr>
			<th> Password : 
				<textarea autocomplete="arun"> </textarea> </th>
				<!--cell> list box </cell-->
		</tr>
	</table>
</center>

app/views/pages/home.html.erb
<h1> This is my alphahome</h1>

<!--%= link_to 'About', welcome_alphaabout_path %-->
<%= link_to 'About', alphaabout_path %>
<br>
<br>
<%= link_to 'First', alphafirst_path %>